# Data Manipulation with pandas
Run the hidden code cell below to import the data used in this course.

In [20]:
# Import the course packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Import the four datasets
avocado = pd.read_csv("datasets/avocado.csv")
homelessness = pd.read_csv("datasets/homelessness.csv")
temperatures = pd.read_csv("datasets/temperatures.csv")
walmart = pd.read_csv("datasets/walmart.csv")

## 1. Exploring DataFrame:
You can learn a lot about a dataframe with the following methods and attributes:
- `.info()`: provides a summary of the DataFrame, including column names, data types, and missing values.
- `.shape`: returns the dimensions of the DataFrame as a tuple: `(umber of rows, number of columns)`.
- `.describe()`: generates summary statistics for numerical columns, such as count, mean, and median.

In [3]:
# Printing the first n rows of a dataframe:
print(homelessness.head(8))

               region        state  individuals  family_members  state_pop
0  East South Central      Alabama       2570.0           864.0    4887681
1             Pacific       Alaska       1434.0           582.0     735139
2            Mountain      Arizona       7259.0          2606.0    7158024
3  West South Central     Arkansas       2280.0           432.0    3009733
4             Pacific   California     109008.0         20964.0   39461588
5            Mountain     Colorado       7607.0          3250.0    5691287
6         New England  Connecticut       2280.0          1696.0    3571520
7      South Atlantic     Delaware        708.0           374.0     965479

In [4]:
homelessness.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   region          51 non-null     object
 1   state           51 non-null     object
 2   individuals     51 non-null     float64
 3   family_members  51 non-null     float64
 4   state_pop       51 non-null     int64
dtypes: float64(2), int64(1), object(2)
memory usage: 2.1+ KB

In [5]:
# using the shape
homelessness.shape

(51, 5)

In [6]:
print(type(homelessness.describe()))
print(homelessness.describe())

<class 'pandas.core.frame.DataFrame'>
         individuals  family_members     state_pop
count      51.000000       51.000000  5.100000e+01
mean     7225.784314     3504.882353  6.405637e+06
std     15991.025083     7805.411811  7.327258e+06
min       434.000000       75.000000  5.776010e+05
25%      1446.500000      592.000000  1.777414e+06
50%      3082.000000     1482.000000  4.461153e+06
75%      6781.500000     3196.000000  7.340946e+06
max    109008.000000    52070.000000  3.946159e+07

### 1.1. Getting Parts of a DF:
You can get parts (components) of dataframe not the information about it with:
- `.values`: returns the data in a 2D numpy array
- `.columns`: returns the columns as a list
- `.index`: returns the index as a list

In [7]:
# Accessing column names and row labels
print("The columns: ", homelessness.columns)
print("The index: ",  homelessness.index)
print("The values: ", homelessness.values)

The columns:  Index(['region', 'state', 'individuals', 'family_members', 'state_pop'], dtype='object')
The index:  RangeIndex(start=0, stop=51, step=1)
The values:  [['East South Central' 'Alabama' 2570.0 864.0 4887681]
 ['Pacific' 'Alaska' 1434.0 582.0 735139]
 ['Mountain' 'Arizona' 7259.0 2606.0 7158024]
 ['West South Central' 'Arkansas' 2280.0 432.0 3009733]
 ['Pacific' 'California' 109008.0 20964.0 39461588]
 ['Mountain' 'Colorado' 7607.0 3250.0 5691287]
 ['New England' 'Connecticut' 2280.0 1696.0 3571520]
 ['South Atlantic' 'Delaware' 708.0 374.0 965479]
 ['South Atlantic' 'District of Columbia' 3770.0 3134.0 701547]
 ['South Atlantic' 'Florida' 21443.0 9587.0 21244317]
 ['South Atlantic' 'Georgia' 6943.0 2556.0 10511131]
 ['Pacific' 'Hawaii' 4131.0 2399.0 1420593]
 ['Mountain' 'Idaho' 1297.0 715.0 1750536]
 ['East North Central' 'Illinois' 6752.0 3891.0 12723071]
 ['East North Central' 'Indiana' 3776.0 1482.0 6695497]
 ['West North Central' 'Iowa' 1711.0 1038.0 3148618]
 ['West North Central' 'Kansas' 1443.0 773.0 2911359]
 ['East South Central' 'Kentucky' 2735.0 953.0 4461153]
 ['West South Central' 'Louisiana' 2540.0 519.0 4659690]
 ['New England' 'Maine' 1450.0 1066.0 1339057]
 ['South Atlantic' 'Maryland' 4914.0 2230.0 6035802]
 ['New England' 'Massachusetts' 6811.0 13257.0 6882635]
 ['East North Central' 'Michigan' 5209.0 3142.0 9984072]
 ['West North Central' 'Minnesota' 3993.0 3250.0 5606249]
 ['East South Central' 'Mississippi' 1024.0 328.0 2981020]
 ['West North Central' 'Missouri' 3776.0 2107.0 6121623]
 ['Mountain' 'Montana' 983.0 422.0 1060665]
 ['West North Central' 'Nebraska' 1745.0 676.0 1925614]
 ['Mountain' 'Nevada' 7058.0 486.0 3027341]
 ['New England' 'New Hampshire' 835.0 615.0 1353465]
 ['Mid-Atlantic' 'New Jersey' 6048.0 3350.0 8886025]
 ['Mountain' 'New Mexico' 1949.0 602.0 2092741]
 ['Mid-Atlantic' 'New York' 39827.0 52070.0 19530351]
 ['South Atlantic' 'North Carolina' 6451.0 2817.0 10381615]
 ['West North Central' 'North Dakota' 467.0 75.0 758080]
 ['East North Central' 'Ohio' 6929.0 3320.0 11676341]
 ['West South Central' 'Oklahoma' 2823.0 1048.0 3940235]
 ['Pacific' 'Oregon' 11139.0 3337.0 4181886]
 ['Mid-Atlantic' 'Pennsylvania' 8163.0 5349.0 12800922]
 ['New England' 'Rhode Island' 747.0 354.0 1058287]
 ['South Atlantic' 'South Carolina' 3082.0 851.0 5084156]
 ['West North Central' 'South Dakota' 836.0 323.0 878698]
 ['East South Central' 'Tennessee' 6139.0 1744.0 6771631]
 ['West South Central' 'Texas' 19199.0 6111.0 28628666]
 ['Mountain' 'Utah' 1904.0 972.0 3153550]
 ['New England' 'Vermont' 780.0 511.0 624358]
 ['South Atlantic' 'Virginia' 3928.0 2047.0 8501286]
 ['Pacific' 'Washington' 16424.0 5880.0 7523869]
 ['South Atlantic' 'West Virginia' 1021.0 222.0 1804291]
 ['East North Central' 'Wisconsin' 2740.0 2167.0 5807406]
 ['Mountain' 'Wyoming' 434.0 205.0 577601]]

## 2. Sorting and Subsetting:

### 2.1. Sorting Rows:
- `.sort_values('columns')` or `.sort_values(['column1', 'column2'])`

In [8]:
print(homelessness.head())

               region       state  individuals  family_members  state_pop
0  East South Central     Alabama       2570.0           864.0    4887681
1             Pacific      Alaska       1434.0           582.0     735139
2            Mountain     Arizona       7259.0          2606.0    7158024
3  West South Central    Arkansas       2280.0           432.0    3009733
4             Pacific  California     109008.0         20964.0   39461588

Sorting in ascending order

In [9]:
newHomelessness = homelessness.sort_values('state_pop')
print(newHomelessness.head())

                region                 state  ...  family_members  state_pop
50            Mountain               Wyoming  ...           205.0     577601
45         New England               Vermont  ...           511.0     624358
8       South Atlantic  District of Columbia  ...          3134.0     701547
1              Pacific                Alaska  ...           582.0     735139
34  West North Central          North Dakota  ...            75.0     758080

[5 rows x 5 columns]

You can sort in descending order:

In [10]:
# Sorting in descending order:
newHomelessnessDesc = homelessness.sort_values('state_pop', ascending = False)
print(newHomelessnessDesc.head())

                region         state  individuals  family_members  state_pop
4              Pacific    California     109008.0         20964.0   39461588
43  West South Central         Texas      19199.0          6111.0   28628666
9       South Atlantic       Florida      21443.0          9587.0   21244317
32        Mid-Atlantic      New York      39827.0         52070.0   19530351
38        Mid-Atlantic  Pennsylvania       8163.0          5349.0   12800922

If you want to sort with multiple columns:

In [11]:
newHomelessnessAscTwo = homelessness.sort_values(['state_pop', 'family_members'], ascending = [True, True])
print(newHomelessnessAscTwo.head(10))

                region                 state  ...  family_members  state_pop
50            Mountain               Wyoming  ...           205.0     577601
45         New England               Vermont  ...           511.0     624358
8       South Atlantic  District of Columbia  ...          3134.0     701547
1              Pacific                Alaska  ...           582.0     735139
34  West North Central          North Dakota  ...            75.0     758080
41  West North Central          South Dakota  ...           323.0     878698
7       South Atlantic              Delaware  ...           374.0     965479
39         New England          Rhode Island  ...           354.0    1058287
26            Mountain               Montana  ...           422.0    1060665
19         New England                 Maine  ...          1066.0    1339057

[10 rows x 5 columns]

In [12]:
newHomelessnessDescTwo = homelessness.sort_values(['state_pop', 'family_members'], ascending = [False, False])
print(newHomelessnessDescTwo.head())

                region         state  individuals  family_members  state_pop
4              Pacific    California     109008.0         20964.0   39461588
43  West South Central         Texas      19199.0          6111.0   28628666
9       South Atlantic       Florida      21443.0          9587.0   21244317
32        Mid-Atlantic      New York      39827.0         52070.0   19530351
38        Mid-Atlantic  Pennsylvania       8163.0          5349.0   12800922

In [13]:
# Two columns but one is ascending one is descending
newHomelessnessDiffTwo = homelessness.sort_values(['state_pop', 'family_members'], ascending = [True, False])
print(newHomelessnessDiffTwo.head())

                region                 state  ...  family_members  state_pop
50            Mountain               Wyoming  ...           205.0     577601
45         New England               Vermont  ...           511.0     624358
8       South Atlantic  District of Columbia  ...          3134.0     701547
1              Pacific                Alaska  ...           582.0     735139
34  West North Central          North Dakota  ...            75.0     758080

[5 rows x 5 columns]

**Anki this:**<br>
You sort the df with multiple columns, you pass a list, incidentally you also pass a list about how you want to sort the columns.

### 2.2. Subsetting Rows Based on Conditions:

- When we say subsetting, you are getting a part of a set. So if our entire dataframe is the universal set then we can subset from it.

In [14]:
# Rewrite code below
print(avocado.head(10))
print(avocado.tail())

         date          type  year  avg_price   size      nb_sold
0  2015-12-27  conventional  2015       0.95  small   9626901.09
1  2015-12-20  conventional  2015       0.98  small   8710021.76
2  2015-12-13  conventional  2015       0.93  small   9855053.66
3  2015-12-06  conventional  2015       0.89  small   9405464.36
4  2015-11-29  conventional  2015       0.99  small   8094803.56
5  2015-11-22  conventional  2015       0.96  small   8571849.80
6  2015-11-15  conventional  2015       0.92  small   9907981.27
7  2015-11-08  conventional  2015       0.97  small   9991330.31
8  2015-11-01  conventional  2015       0.97  small  10138703.85
9  2015-10-25  conventional  2015       1.04  small   8683958.80
            date     type  year  avg_price         size  nb_sold
1009  2018-02-04  organic  2018       1.53  extra_large  1703.52
1010  2018-01-28  organic  2018       1.61  extra_large  1270.61
1011  2018-01-21  organic  2018       1.63  extra_large  1490.02
1012  2018-01-14  organic  2018       1.59  extra_large  1580.01
1013  2018-01-07  organic  2018       1.51  extra_large  1289.07

In [15]:
# Let say for example, you want to just get the set of avocados sold that are small
smallAvocadoBool = avocado['size'] == 'small' # this will return a boolean series
print(smallAvocadoBool)

0        True
1        True
2        True
3        True
4        True
        ...
1009    False
1010    False
1011    False
1012    False
1013    False
Name: size, Length: 1014, dtype: bool

In [16]:
# Now, what will happen if we use this boolean array to subset
smallAvocadoDf = avocado[smallAvocadoBool]
print(smallAvocadoDf.head())
print(smallAvocadoDf.tail())

         date          type  year  avg_price   size     nb_sold
0  2015-12-27  conventional  2015       0.95  small  9626901.09
1  2015-12-20  conventional  2015       0.98  small  8710021.76
2  2015-12-13  conventional  2015       0.93  small  9855053.66
3  2015-12-06  conventional  2015       0.89  small  9405464.36
4  2015-11-29  conventional  2015       0.99  small  8094803.56
           date     type  year  avg_price   size    nb_sold
333  2018-02-04  organic  2018       1.53  small  117922.52
334  2018-01-28  organic  2018       1.61  small  118616.17
335  2018-01-21  organic  2018       1.63  small  108705.28
336  2018-01-14  organic  2018       1.59  small  145680.62
337  2018-01-07  organic  2018       1.51  small  129541.43

What if you are only interested in avocados sold that are from 2017 to the latest

In [17]:
avocadosLatest = avocado[avocado['date'] >= '2017-01-01']
print(avocadosLatest)

            date          type  year  avg_price         size      nb_sold
104   2017-12-31  conventional  2017       0.98        small  13109617.49
105   2017-12-24  conventional  2017       1.18        small  10027319.18
106   2017-12-17  conventional  2017       1.07        small  10704214.26
107   2017-12-10  conventional  2017       1.03        small  11943914.54
108   2017-12-03  conventional  2017       1.09        small  11746980.00
...          ...           ...   ...        ...          ...          ...
1009  2018-02-04       organic  2018       1.53  extra_large      1703.52
1010  2018-01-28       organic  2018       1.61  extra_large      1270.61
1011  2018-01-21       organic  2018       1.63  extra_large      1490.02
1012  2018-01-14       organic  2018       1.59  extra_large      1580.01
1013  2018-01-07       organic  2018       1.51  extra_large      1289.07

[390 rows x 6 columns]

### 2.3. Subsetting w/ Multiple Conditions:
- Remember that logical operators **between** two series still result to the resulting series therefore if you pass it to the dataframe it still returns a dataframe.

In [18]:
import numpy
organicSmallBool = numpy.logical_and(avocado['type'] == 'organic', avocado['size'] == 'small')
print(organicSmallBool[169])

True

You can simplify the above by using the .isin() method
- `.isin():` takes a list of argument where the conditions matches.
- It's like doing `WHERE color IN ('black', 'brown')` in SQL (anki this)

```python
# Filtering for specific colors
# this works like OR
black_brown_dogs = dogs[dogs['color'].isin(['black', 'brown'])]
print(black_brown_dogs)
```

### 2.4. Adding New Columns:
You can add new column with `df['newCol'] = calculation`

- You can opt for this if you want to for instance get the BMI convert inches to meters.

# Difficult examples, must be revisited.

"Which state has the highest number of homeless individuals per 10,000 people in the state?" Combine your new pandas skills to find out.

- Add a column to homelessness, indiv_per_10k, containing the number of homeless individuals per ten thousand people in each state, using state_pop for state population.
- Subset rows where indiv_per_10k is higher than 20, assigning to high_homelessness.
- Sort high_homelessness by descending indiv_per_10k, assigning to high_homelessness_srt.
- Select only the state and indiv_per_10k columns of high_homelessness_srt and save as result. Look at the result.

In [11]:
# Create indiv_per_10k col as homeless individuals per 10k state pop
homelessness["indiv_per_10k"] = 10000 * homelessness['individuals'] / homelessness['state_pop'] 

# Subset rows for indiv_per_10k greater than 20
high_homelessness = homelessness[homelessness['indiv_per_10k'] > 20]

# Sort high_homelessness by descending indiv_per_10k
high_homelessness_srt = high_homelessness.sort_values('indiv_per_10k', ascending = False)

# From high_homelessness_srt, select the state and indiv_per_10k cols
result = high_homelessness_srt[['state', 'indiv_per_10k']]

# See the result
print(result)

                   state  indiv_per_10k
8   District of Columbia      53.738381
11                Hawaii      29.079406
4             California      27.623825
37                Oregon      26.636307
28                Nevada      23.314189
47            Washington      21.829195
32              New York      20.392363

# Chapter 2:

## 1. Summarizing Numerical Data
There are methods you can use to get summary statistics:
- `.mean()`
- `.median()`
- `.mode()`
- `.min()`
- `.var()`
- `.std()`
- `.quantile()`

In [ ]:
# Example of summary statistics
mean_weight = dogs['weight_kg'].mean()
median_weight = dogs['weight_kg'].median()
max_weight = dogs['weight_kg'].max()
min_weight = dogs['weight_kg'].min()
mean_weight, median_weight, max_weight, min_weight

In [7]:
homelessness.head()

               region       state  individuals  family_members  state_pop
0  East South Central     Alabama       2570.0           864.0    4887681
1             Pacific      Alaska       1434.0           582.0     735139
2            Mountain     Arizona       7259.0          2606.0    7158024
3  West South Central    Arkansas       2280.0           432.0    3009733
4             Pacific  California     109008.0         20964.0   39461588

## 2. Custome Aggregation with .agg()
- Use `.agg()` to apply custom functions across DataFrame columns.
- Create a custom function for specific calculations, such as the 30th percentile.
- `df['col'].agg(func)`

In [ ]:
# Define a custom function to calculate 30th percentile
def pct30(column):
    return column.quantile(0.3)

# Applying custom function to weight column
thirtieth_percentile_weight = dogs['weight_kg'].agg(pct30)
thirtieth_percentile_weight

**Aggregating Multiple Columns and Functions**
- With `.agg(),` apply multiple functions on multiple columns at once.
- **Example:** Calculate both the 30th and 40th percentiles.

In [ ]:
# Define additional custom functions
def pct40(column):
    return column.quantile(0.4)

# Apply multiple custom functions on weight and height columns
dogs[['weight_kg', 'height_cm']].agg([pct30, pct40])

In [ ]:
# you can also add functions from numpy
dogs[['weight_kg', 'height_cm']].agg([pct30, pct40, np.median])

## 3. Cumulative Statistics
Cumulative statistics include: 
- `.cumsum()` for cumulative sums
- `.cummax()` for cumulative maximum 
- `.cummin()` for cumulative minimum 
- `.cumprod()` for cumulative product

In [ ]:
# Calculating cumulative sum for weight column
dogs['cumulative_weight'] = dogs['weight_kg'].cumsum()
dogs.head()

## 4. Counting
- This section focuses on counting occurrences within categorical columns to summarize and analyze data distributions effectively.

### 4.1. Dropping Duplicates:
If you are interested in counting unique value in a column of course you want to drop duplicates. <br>
**Single column**: Passes a column name into the `subset.`
- `df.drop_duplicates(subset = 'col')`

**What happens if you drop duplicates in a column, let's say you have a col 1 with duplicates and in col 2 they are different, what will happen to the values in col 2??**

In [15]:
# before dropping the duplicates
print("Before dropping the duplicates", homelessness.shape)
uniqueHome = homelessness.drop_duplicates(subset = 'region')
print("After dropping the duplicates",uniqueHome.shape)

NameError: name 'homelessness' is not defined

mawawala lahat, yung unang occurence yung mag-aappear

**Multiple Column Duplicates**: Pass a list to the `subset`
- `df.drop_duplicates(subset = ['col1', 'col2'])`

What is the purpose of this having multiple columns?
Kasi kapag isang column lang you may have the smae value sa column na yun, pagdating sa ibang column, magkaiba pala sila?! edi di sila duplicates talaga.

so we can do this para malaman talaga kung may duplicates.

In [16]:
uniqueHome2 = homelessness.drop_duplicates(subset = homelessness.columns)
print(homelessness.shape)
print(uniqueHome2.shape) # must return the same shape if no duplicates

(51, 5)
(51, 5)

In [ ]:
# Drop duplicates based on the name column
unique_dogs = vet_visits.drop_duplicates(subset='name')

# Drop duplicates based on both name and breed columns
unique_dogs_by_breed = vet_visits.drop_duplicates(subset=['name', 'breed'])
unique_dogs_by_breed.head()

### 4.2. Counting Categorical Values:
(ANKI THIS)**In counting**, how do you know which column to use?<br>You use the colum that is a category
- Use `.value_counts()` to count occurrences in a categorical column, like breed.
- The `sort` argument in `.value_counts()` can order the counts from largest to smallest.

In [ ]:
# Count occurrences of each breed
breed_counts = unique_dogs_by_breed['breed'].value_counts(sort=True)

### 4.3. Calculating Proportions
- Set normalize=True in .value_counts() to return proportions instead of counts.

In [ ]:
# Get the proportion of each breed in the dataset
breed_proportions = unique_dogs_by_breed['breed'].value_counts(normalize=True)

## 5. GROUPED Summary Statistics
Grouped summary statistics allow you to compare metrics across different groups within a dataset, revealing insights like average values for each category or distribution patterns across subsets.

- This is the same with the GROUP BY of SQL

### 5.1. Understanding .groupby()

What does the df.groupby('col') return?
it kinda returns a data frame but specifically its groupby

In [22]:
homewGroup = homelessness.groupby('region')
print(type(homewGroup))
pacificGroup = homewGroup.get_group('Pacific')
print(type(pacificGroup))
print(pacificGroup)
print(pacificGroup.shape)

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>
<class 'pandas.core.frame.DataFrame'>
     region       state  individuals  family_members  state_pop
1   Pacific      Alaska       1434.0           582.0     735139
4   Pacific  California     109008.0         20964.0   39461588
11  Pacific      Hawaii       4131.0          2399.0    1420593
37  Pacific      Oregon      11139.0          3337.0    4181886
47  Pacific  Washington      16424.0          5880.0    7523869
(5, 5)

So if the pacificGroup is a dataframe then you can get the summary statistics in that dataframe.

In [23]:
# let's say you want to get the mean from the pacificGroup
pacificGroup['state_pop'].mean()

10664615.0

or You can do the same thing directly with the groupby.

In [5]:
print(homelessness.groupby('region')['state_pop'].mean())
print(type(homelessness.groupby('region')[['state_pop', 'state']]))

region
East North Central    9.377277e+06
East South Central    4.775371e+06
Mid-Atlantic          1.373910e+07
Mountain              3.063968e+06
New England           2.471554e+06
Pacific               1.066462e+07
South Atlantic        7.247736e+06
West North Central    3.050034e+06
West South Central    1.005958e+07
Name: state_pop, dtype: float64
<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

### 5.2. Calculating without a GROUPBY

Well, first you are subsetting your dataframe to include only types A, B, or C. You do that by passing a boolean series to your dataframe so that only those with true values (A, B, or C) will be retrieved. <br>After getting a dataframe you then subset a column "weekly_sales" and get its .sum()

In [ ]:
# EXPLAIN THIS with Anki

# Calc total weekly sales
sales_all = sales["weekly_sales"].sum()

# Subset for type A stores, calc total weekly sales
sales_A = sales[sales["type"] == "A"]["weekly_sales"].sum()

# Subset for type B stores, calc total weekly sales
sales_B = sales[sales["type"] == 'B']['weekly_sales'].sum()

# Subset for type C stores, calc total weekly sales
sales_C = sales[sales['type'] == 'C']['weekly_sales'].sum()
print(sales_A)
# Get proportion for each type
# sales_propn_by_type = [sales_A, sales_B, sales_C] / 
# print(sales_propn_by_type)

NameError: name 'sales' is not defined

### 5.3. Calculating aggreagtes using .groupby()

- You can use `.groupby()` to break down data into groups based on a categorical variable and then calculate metrics for each group.

In [6]:
# for example if you want to calculate the median in a column of a group 
print(homelessness.head())
mediansGroup = homelessness.groupby('region')['family_members'].median()
print(mediansGroup)
print(mediansGroup['Pacific'])

               region       state  individuals  family_members  state_pop
0  East South Central     Alabama       2570.0           864.0    4887681
1             Pacific      Alaska       1434.0           582.0     735139
2            Mountain     Arizona       7259.0          2606.0    7158024
3  West South Central    Arkansas       2280.0           432.0    3009733
4             Pacific  California     109008.0         20964.0   39461588
region
East North Central    3142.0
East South Central     908.5
Mid-Atlantic          5349.0
Mountain               658.5
New England            840.5
Pacific               3337.0
South Atlantic        2230.0
West North Central     773.0
West South Central     783.5
Name: family_members, dtype: float64
3337.0

### 5.4. Aggregating Multiple Statistics on Grouped Data
- The `.agg()` method allows for applying multiple functions to each group. Pass a list of functions to `.agg()` to calculate different statistics like minimum, maximum, and sum.

In [7]:
# what if you want to get the min, max, and mean of each group:
aggGroups = homelessness.groupby('region')['family_members'].agg(['min', 'max', 'mean'])
print(aggGroups)

                       min      max          mean
region
East North Central  1482.0   3891.0   2800.400000
East South Central   328.0   1744.0    972.250000
Mid-Atlantic        3350.0  52070.0  20256.333333
Mountain             205.0   3250.0   1157.250000
New England          354.0  13257.0   2916.500000
Pacific              582.0  20964.0   6632.400000
South Atlantic       222.0   9587.0   2646.444444
West North Central    75.0   3250.0   1177.428571
West South Central   432.0   6111.0   2027.500000

### 5.5. Grouping by Multiple Variables
- To calculate grouped statistics for combinations of multiple variables, pass a list of columns to .groupby().

- Let's say you are grouping with two columns, it can look like this:

| Category | Subcategory | Value |
|----------|-------------|-------|
| A        | X           | 40    |
| A        | Y           | 20    |
| B        | X           | 50    |
| B        | Y           | 40    |
| C        | X           | 150   |
| C        | Y           | 60    |

In [16]:
print(avocado.head())

         date          type  year  avg_price   size     nb_sold
0  2015-12-27  conventional  2015       0.95  small  9626901.09
1  2015-12-20  conventional  2015       0.98  small  8710021.76
2  2015-12-13  conventional  2015       0.93  small  9855053.66
3  2015-12-06  conventional  2015       0.89  small  9405464.36
4  2015-11-29  conventional  2015       0.99  small  8094803.56

In [8]:
# let us group the avocado dataframe by type and then by year
print(avocado.groupby(['type', 'size'])['nb_sold'].mean())

type          size
conventional  extra_large    9.187040e+05
              large          1.161486e+07
              small          1.201098e+07
organic       extra_large    5.409546e+03
              large          3.082844e+05
              small          1.484047e+05
Name: nb_sold, dtype: float64

### 5.6. Multi-Column Grouping w/ Multi-Column Aggregation
- .groupby() combined with .agg() can handle multiple grouping variables and multiple summary statistics.

In [4]:
import pandas as pd

# Sample data
data = {
    'Category': ['A', 'A', 'A', 'B', 'B', 'C', 'C', 'C'],
    'Subcategory': ['X', 'Y', 'X', 'Y', 'X', 'Y', 'X', 'X'],
    'Value': [10, 20, 30, 40, 50, 60, 70, 80],
    'Quantity': [1, 2, 1, 3, 2, 1, 2, 3]
}
df = pd.DataFrame(data)
print(df)
# Group by 'Category' and 'Subcategory' and apply multiple aggregatis
grouped = df.groupby(['Category', 'Subcategory']).agg(['sum', 'mean', 'count']).reset_index()
print(grouped)

  Category Subcategory  Value  Quantity
0        A           X     10         1
1        A           Y     20         2
2        A           X     30         1
3        B           Y     40         3
4        B           X     50         2
5        C           Y     60         1
6        C           X     70         2
7        C           X     80         3
  Category Subcategory Value             Quantity
                         sum  mean count      sum mean count
0        A           X    40  20.0     2        2  1.0     2
1        A           Y    20  20.0     1        2  2.0     1
2        B           X    50  50.0     1        2  2.0     1
3        B           Y    40  40.0     1        3  3.0     1
4        C           X   150  75.0     2        5  2.5     2
5        C           Y    60  60.0     1        1  1.0     1

| Category | Subcategory | Value (sum) | Value (mean) | Quantity (sum) | Quantity (count) |
|----------|-------------|-------------|--------------|----------------|------------------|
| A        | X           | 40          | 20.0         | 2              | 2                |
| A        | Y           | 20          | 20.0         | 2              | 1                |
| B        | X           | 50          | 50.0         | 2              | 1                |
| B        | Y           | 40          | 40.0         | 3              | 1                |
| C        | X           | 150         | 75.0         | 5              | 3                |
| C        | Y           | 60          | 60.0         | 1              | 1                |

## 6. Pivot Tables
- The .pivot_table() method can replace .groupby() for simple grouped statistics.
- When does your pivot value return a NaN if for example in avocado: your conventional does not have a small size but the column has a small size

### 6.1. Basic Pivot Tables
- Use the `values` argument for the column you want to summarize and `index` for the column to group by. By default, `.pivot_table()` computes the mean for each group.

In [12]:
# remember that you can do this with groupby()
print(type(avocado.groupby('type')['nb_sold'].mean()))
print(avocado.groupby('type')['nb_sold'].mean())

<class 'pandas.core.series.Series'>
type
conventional    8.181515e+06
organic         1.540329e+05
Name: nb_sold, dtype: float64

In [14]:
# you can also do it with pivot tables
pvTableAvocado = avocado.pivot_table(index = 'type', values = 'nb_sold')
print(type(pvTableAvocado))
print(pvTableAvocado)

<class 'pandas.core.frame.DataFrame'>
                   nb_sold
type
conventional  8.181515e+06
organic       1.540329e+05

### 6.3. Customizing Aggregation Function
- To use a different statistic, pass the desired function to the `aggfunc` argument.

In [18]:
# customizing aggregation function
# if you want the above code to be a median instead of a mean
print(avocado.pivot_table(index = 'type', values = 'nb_sold', aggfunc = np.median))

                  nb_sold
type
conventional  10197890.05
organic         132040.04

### 6.4. Multiple Statistics
- For multiple statistics, pass a list of functions to `aggfunc`.

In [21]:
# If you want to calculate mean and median of the type of avocados
print(avocado.pivot_table(index = 'type', values = 'nb_sold', aggfunc = [np.median, np.mean]))

                   median          mean
                  nb_sold       nb_sold
type
conventional  10197890.05  8.181515e+06
organic         132040.04  1.540329e+05

In [8]:
temperatures.head()

         date     city        country  avg_temp_c
0  2000-01-01  Abidjan  Côte D'Ivoire      27.293
1  2000-02-01  Abidjan  Côte D'Ivoire      27.685
2  2000-03-01  Abidjan  Côte D'Ivoire      29.061
3  2000-04-01  Abidjan  Côte D'Ivoire      28.162
4  2000-05-01  Abidjan  Côte D'Ivoire      27.547

# Chapter 3: Slicing and Indexing DataFrames

 We will be using the walmart dataframe for this chapter

### 1. Explicit Indexes in Pandas
- `.columns` holds the Index object of column names.
- `.index` holds the Index object of row labels.

In [4]:
print("Are the indexes:", walmart.index)
print("Are the columns:", walmart.columns)

Are the indexes: RangeIndex(start=0, stop=10774, step=1)
Are the columns: Index(['store', 'type', 'department', 'date', 'weekly_sales', 'is_holiday',
       'temperature_c', 'fuel_price_usd_per_l', 'unemployment'],
      dtype='object')

### 1.1. Setting a Column as the Index
- Use `.set_index()` to designate a column as the index.

In [8]:
# the current index of the walmart df are numbers
walmartwIndex = walmart.set_index('store')
walmartwIndexDuplicate = walmart.set_index(walmart['store'])
print(walmartwIndex, walmartwIndexDuplicate)

      type  department  ... fuel_price_usd_per_l  unemployment
store                   ...
1        A           1  ...             0.679451         8.106
1        A           1  ...             0.693452         8.106
1        A           1  ...             0.718284         7.808
1        A           1  ...             0.748928         7.808
1        A           1  ...             0.714586         7.808
...    ...         ...  ...                  ...           ...
39       A          99  ...             0.834256         7.716
39       A          99  ...             0.887619         7.244
39       A          99  ...             0.911922         6.989
39       A          99  ...             0.860145         6.623
39       A          99  ...             0.955511         6.228

[10774 rows x 8 columns]        store type  ...  fuel_price_usd_per_l unemployment
store              ...
1          1    A  ...              0.679451        8.106
1          1    A  ...              0.693452        8.106
1          1    A  ...              0.718284        7.808
1          1    A  ...              0.748928        7.808
1          1    A  ...              0.714586        7.808
...      ...  ...  ...                   ...          ...
39        39    A  ...              0.834256        7.716
39        39    A  ...              0.887619        7.244
39        39    A  ...              0.911922        6.989
39        39    A  ...              0.860145        6.623
39        39    A  ...              0.955511        6.228

[10774 rows x 9 columns]

### 1.2. Dropping an Index
- Reset the index with `.reset_index(),` moving it back as a regular column.
- Use `drop=True` in `.reset_index()` to remove the index entirely.

In [11]:
walmartwIndex.reset_index().head()

   store type  department  ... temperature_c  fuel_price_usd_per_l  unemployment
0      1    A           1  ...      5.727778              0.679451         8.106
1      1    A           1  ...      8.055556              0.693452         8.106
2      1    A           1  ...     16.816667              0.718284         7.808
3      1    A           1  ...     22.527778              0.748928         7.808
4      1    A           1  ...     27.050000              0.714586         7.808

[5 rows x 9 columns]

In [12]:
walmartwIndex.reset_index(drop = True).head()

  type  department  ... fuel_price_usd_per_l  unemployment
0    A           1  ...             0.679451         8.106
1    A           1  ...             0.693452         8.106
2    A           1  ...             0.718284         7.808
3    A           1  ...             0.748928         7.808
4    A           1  ...             0.714586         7.808

[5 rows x 8 columns]

## 2. Multi-Level Indexes
We will use the temperatures here

In [14]:
temperatures.head()

         date     city        country  avg_temp_c
0  2000-01-01  Abidjan  Côte D'Ivoire      27.293
1  2000-02-01  Abidjan  Côte D'Ivoire      27.685
2  2000-03-01  Abidjan  Côte D'Ivoire      29.061
3  2000-04-01  Abidjan  Côte D'Ivoire      28.162
4  2000-05-01  Abidjan  Côte D'Ivoire      27.547

### 2.1. Multi-Level Indexes (Hierarchical Indexes)
- Set multiple columns as a multi-level (hierarchical) index by passing a list to `.set_index().`

In [25]:
mLevelTemp = temperatures.set_index(['country', 'city'])
print(mLevelTemp.head())
print(type(mLevelTemp)) # DataFrame to kasi Index niya lang naman yung country and city e

                             date  avg_temp_c
country       city
Côte D'Ivoire Abidjan  2000-01-01      27.293
              Abidjan  2000-02-01      27.685
              Abidjan  2000-03-01      29.061
              Abidjan  2000-04-01      28.162
              Abidjan  2000-05-01      27.547
<class 'pandas.core.frame.DataFrame'>

**Note to self:**<br>That seems like a groupby with multiple variables:

In [27]:
temperatures.groupby(['country', 'city']).get_group(('Côte D\'Ivoire','Abidjan')).head() # this one kinuha mo lang yung isang dataframe from a collection of dataframe

         date     city        country  avg_temp_c
0  2000-01-01  Abidjan  Côte D'Ivoire      27.293
1  2000-02-01  Abidjan  Côte D'Ivoire      27.685
2  2000-03-01  Abidjan  Côte D'Ivoire      29.061
3  2000-04-01  Abidjan  Côte D'Ivoire      28.162
4  2000-05-01  Abidjan  Côte D'Ivoire      27.547

### 2.2. Subsetting Multi-Level Indexes
- If you want to subset just the outerlevel you can use a list
- If both the outer and the inner, use a tuple, specifying outer and inner

In [3]:
# Index temperatures by country & city
temperatures_ind = temperatures.set_index(['country', 'city'])

# List of tuples: Brazil, Rio De Janeiro & Pakistan, Lahore
rows_to_keep = [('Brazil', 'Rio De Janeiro'), ('Pakistan', 'Lahore')]

# Subset for rows to keep
print(temperatures_ind.loc[rows_to_keep])

                               date  avg_temp_c
country  city
Brazil   Rio De Janeiro  2000-01-01      25.974
         Rio De Janeiro  2000-02-01      26.699
         Rio De Janeiro  2000-03-01      26.270
         Rio De Janeiro  2000-04-01      25.750
         Rio De Janeiro  2000-05-01      24.356
...                             ...         ...
Pakistan Lahore          2013-05-01      33.457
         Lahore          2013-06-01      34.456
         Lahore          2013-07-01      33.279
         Lahore          2013-08-01      31.511
         Lahore          2013-09-01         NaN

[330 rows x 2 columns]

### 2.3. Sorting by Index values
- Remember we have `.sort_values()`
- Guess what, we also have `sort_index()`

- Sort rows by index with `.sort_index(),` which defaults to sorting outer-to-inner levels.
- Control the sort with level and ascending parameters.

In [31]:
# Sort temperatures_ind by index values
print(temperatures_ind.sort_index())

                          date  avg_temp_c
country     city
Afghanistan Kabul   2000-01-01       3.326
            Kabul   2000-02-01       3.454
            Kabul   2000-03-01       9.612
            Kabul   2000-04-01      17.925
            Kabul   2000-05-01      24.658
...                        ...         ...
Zimbabwe    Harare  2013-05-01      18.298
            Harare  2013-06-01      17.020
            Harare  2013-07-01      16.299
            Harare  2013-08-01      19.232
            Harare  2013-09-01         NaN

[16500 rows x 2 columns]

In [32]:
# Sort temperatures_ind by index values at the city level
print(temperatures_ind.sort_index(level = 'city'))

                             date  avg_temp_c
country       city
Côte D'Ivoire Abidjan  2000-01-01      27.293
              Abidjan  2000-02-01      27.685
              Abidjan  2000-03-01      29.061
              Abidjan  2000-04-01      28.162
              Abidjan  2000-05-01      27.547
...                           ...         ...
China         Xian     2013-05-01      18.979
              Xian     2013-06-01      23.522
              Xian     2013-07-01      25.251
              Xian     2013-08-01      24.528
              Xian     2013-09-01         NaN

[16500 rows x 2 columns]

In [36]:
# Sort temperatures_ind by country then descending city
print(temperatures_ind.sort_index(level = ['country', 'city'], ascending = [True, False]))

                          date  avg_temp_c
country     city
Afghanistan Kabul   2000-01-01       3.326
            Kabul   2000-02-01       3.454
            Kabul   2000-03-01       9.612
            Kabul   2000-04-01      17.925
            Kabul   2000-05-01      24.658
...                        ...         ...
Zimbabwe    Harare  2013-05-01      18.298
            Harare  2013-06-01      17.020
            Harare  2013-07-01      16.299
            Harare  2013-08-01      19.232
            Harare  2013-09-01         NaN

[16500 rows x 2 columns]

## 3. Slicing Indexes and Columns
- Why is it important to sort indexes before you slice?

In [5]:
temperatures_srt = temperatures_ind.sort_index()
print(temperatures_srt)

                          date  avg_temp_c
country     city
Afghanistan Kabul   2000-01-01       3.326
            Kabul   2000-02-01       3.454
            Kabul   2000-03-01       9.612
            Kabul   2000-04-01      17.925
            Kabul   2000-05-01      24.658
...                        ...         ...
Zimbabwe    Harare  2013-05-01      18.298
            Harare  2013-06-01      17.020
            Harare  2013-07-01      16.299
            Harare  2013-08-01      19.232
            Harare  2013-09-01         NaN

[16500 rows x 2 columns]

### 3.1. Slicing the Outer Index Level with .loc
- With `.loc,` specify start and end index values separated by a colon.
- Note: The final index value is included in the slice.

In [40]:
# Slice the dataframe to include Pakistan to Russia
print(temperatures_srt.loc['Pakistan' : 'Russia'])

                                 date  avg_temp_c
country  city
Pakistan Faisalabad        2000-01-01      12.792
         Faisalabad        2000-02-01      14.339
         Faisalabad        2000-03-01      20.309
         Faisalabad        2000-04-01      29.072
         Faisalabad        2000-05-01      34.845
...                               ...         ...
Russia   Saint Petersburg  2013-05-01      12.355
         Saint Petersburg  2013-06-01      17.185
         Saint Petersburg  2013-07-01      17.234
         Saint Petersburg  2013-08-01      17.153
         Saint Petersburg  2013-09-01         NaN

[1155 rows x 2 columns]

### 3.2. Slicing Inner Index Levels
- For inner levels, pass start and end values as tuples in `.loc`

In [8]:
# Try to subset rows from Lahore to Moscow
print("This does not work if you want to subset with inner level, pass tuples")
print(temperatures_srt.loc['Lahore' : 'Moscow'])

This does not work if you want to subset with inner level, pass tuples
                          date  avg_temp_c
country city
Mexico  Mexico      2000-01-01      12.694
        Mexico      2000-02-01      14.677
        Mexico      2000-03-01      17.376
        Mexico      2000-04-01      18.294
        Mexico      2000-05-01      18.562
...                        ...         ...
Morocco Casablanca  2013-05-01      19.217
        Casablanca  2013-06-01      23.649
        Casablanca  2013-07-01      27.488
        Casablanca  2013-08-01      27.952
        Casablanca  2013-09-01         NaN

[330 rows x 2 columns]

In [9]:
print("This one will work!")
print(temperatures_srt.loc[('Pakistan', 'Lahore'):('Russia', 'Moscow')])

This one will work!
                       date  avg_temp_c
country  city
Pakistan Lahore  2000-01-01      12.792
         Lahore  2000-02-01      14.339
         Lahore  2000-03-01      20.309
         Lahore  2000-04-01      29.072
         Lahore  2000-05-01      34.845
...                     ...         ...
Russia   Moscow  2013-05-01      16.152
         Moscow  2013-06-01      18.718
         Moscow  2013-07-01      18.136
         Moscow  2013-08-01      17.485
         Moscow  2013-09-01         NaN

[660 rows x 2 columns]