# Joining Data with SQL

Here you can access every table used in the course. To access each table, you will need to specify the `world` schema in your queries (e.g., `world.countries` for the `countries` table, and `world.languages` for the `languages` table).

--- 
_Note: When using sample databases such as those that contain course data, you have read-only access. You can run queries, but cannot make any changes such as adding, deleting, or modifying the data (e.g., creating tables, views, etc.)._

# Chapter 1 & 2

## 1. INNER JOIN
- Only returns when there is a match.

In [ ]:
-- Example: Basic INNER JOIN to match records by the "id" field
SELECT left_table.id, left_table.left_val, right_table.right_val
FROM left_table
INNER JOIN right_table
ON left_table.id = right_table.id;

In [10]:
import pandas as pd   
from IPython.display import display_html 

df1 = pd.DataFrame({"id": [1, 2, 3, 4], "left_val": ['L1','L2', 'L3', 'L4']})
df2 = pd.DataFrame({"id": [1, 4, 5, 6], "right_val": ['R1', 'R2', 'R3', 'R4']})
df3 = pd.DataFrame({"id": [1, 4], "left_val": ['L1', 'L4'], "right_val": ['R1', 'R2']})

df1_styler = df1.style.set_table_attributes("style='display:inline'").set_caption('Left table')
df2_styler = df2.style.set_table_attributes("style='display:inline'").set_caption('right table')
df3_styler = df3.style.set_table_attributes("style='display:inline'").set_caption('Result')
display_html(df1_styler._repr_html_()+df2_styler._repr_html_()+df3_styler._repr_html_(), raw=True)

### 1.1. USING() Clause
- When the field names are the same in both tables, you can use the `USING` clause instead of `ON` to simplify the query.

In [14]:
-- Example: Using the USING clause for a simpler INNER JOIN
SELECT p1.country, p1.continent, p2.prime_minister
FROM world.presidents AS p1
INNER JOIN world.prime_ministers AS p2
USING (country);

    country      continent      prime_minister
0     Egypt         Africa       Sherif Ismail
1  Portugal         Europe       Antonio Costa
2     Haiti  North America  Jack Guy Lafontant
3   Vietnam           Asia    Nguyen Xuan Phuc

### 1.2. Multiple JOINS
- SQL allows you to combine multiple joins in a single query to retrieve data from several tables at once.
- You can join one table, then chain another based on the result of the first join.

In [15]:
-- let this be the first JOIN
-- joining countries with both prime ministers and presidents
SELECT 
	p1.country AS countries, 
	p1.continent AS continents, 
	p2.president AS presidents,
	p1.prime_minister AS prime_ministers
FROM world.prime_ministers AS p1
INNER JOIN world.presidents AS p2
ON p1.country = p2.country;

  countries     continents               presidents     prime_ministers
0     Egypt         Africa     Abdel Fattah el-Sisi       Sherif Ismail
1  Portugal         Europe  Marcelo Rebelo de Sousa       Antonio Costa
2   Vietnam           Asia           Tran Dai Quang    Nguyen Xuan Phuc
3     Haiti  North America            Jovenel Moise  Jack Guy Lafontant

- in that result will the next table that we'll join will depend on.

In [1]:
SELECT 
	p1.country AS countries, 
	p1.continent AS continents, 
	p2.president AS presidents,
	p1.prime_minister AS prime_ministers,
	p3.pm_start
FROM world.prime_ministers AS p1
INNER JOIN world.presidents AS p2
ON p1.country = p2.country
-- the table below will depend on the table above
INNER JOIN world.prime_minister_terms AS p3
ON p1.prime_minister = p3.prime_minister;

Empty DataFrame
Columns: [countries, continents, presidents, prime_ministers, pm_start]
Index: []

**Explanation:**
- First, an INNER JOIN is performed between the presidents and prime_ministers tables based on the country field.
- Then, another INNER JOIN is performed between the result of the first join and the prime_minister_terms table, based on the prime_minister field.

### 1.3. Using `ON` (Joining on Multiple Keys)
- This can be done by adding an additional condition using `AND` in the `ON` clause.

sometimes we may have tables such as these:

In [19]:
import pandas as pd   
from IPython.display import display_html 

df1 = pd.DataFrame({"id": [1, 2, 3, 4], "date": ["09/03/19", "04/02/18", "04/03/12", "06/12/22"], "left_val": ['L1','L2', 'L3', 'L4']})
df2 = pd.DataFrame({"id": [1, 1, 4, 4], "date": ["09/03/19", "12/12/20", "06/12/22", "11/08/19"], "right_val": ['R1', 'R1.1', 'R2', 'R2.1']})
df3 = pd.DataFrame({"id": [1, 1, 4, 4], "date": ["09/03/19", "12/12/20", "06/12/22", "11/08/19"], "left_val": ['L1', 'L1', 'L4', 'L4'], "right_val": ['R1', 'R1.1', 'R2', 'R2.1']})

df1_styler = df1.style.set_table_attributes("style='display:inline'").set_caption('Left table')
df2_styler = df2.style.set_table_attributes("style='display:inline'").set_caption('right table')
df3_styler = df3.style.set_table_attributes("style='display:inline'").set_caption('Result')
display_html(df1_styler._repr_html_()+df2_styler._repr_html_()+df3_styler._repr_html_(), raw=True)

If we want to limit this further we can join again ond dates. Where only the same dates from left and rigth tables will be joined to the result table.

In [ ]:
-- We can further filter this with 
SELECT id, date, left_val, right_val
FROM left_table 
INNER JOIN right_table
ON left_table.id = right_table.id
	AND left_table.date = right_table.date;

## 2. LEFT and RIGHT JOIN 
- Allowing us to include non-matching records from one of the tables involved in the join.

### 2.1. The following visualizes the left `JOIN`

In [ ]:
SELECT id, left_table.left_val, right_table.right_val
FROM left_table
LEFT JOIN right_table
ON left_table.id = right_table.id;

In [1]:
import pandas as pd   
from IPython.display import display_html 

df1 = pd.DataFrame({"id": [1, 2, 3, 4], "left_val": ['L1','L2', 'L3', 'L4']})
df2 = pd.DataFrame({"id": [1, 4, 5, 6], "right_val": ['R1', 'R2', 'R3', 'R4']})
df3 = pd.DataFrame({"id": [1, 2, 3, 4], "left_val": ['L1', 'L2', 'L3', 'L4'], "right_val": ['R1', 'NaN', 'NaN','R2']})

df1_styler = df1.style.set_table_attributes("style='display:inline'").set_caption('Left table')
df2_styler = df2.style.set_table_attributes("style='display:inline'").set_caption('right table')
df3_styler = df3.style.set_table_attributes("style='display:inline'").set_caption('Result')
display_html(df1_styler._repr_html_()+df2_styler._repr_html_()+df3_styler._repr_html_(), raw=True)

- A `LEFT JOIN` returns all records from the left table and the matched records from the right table. If there is no match, `NULL` values are returned for columns from the right table.

### 2.2. RIGHT JOIN
- The following visualizes the `RIGHT JOIN`

In [ ]:
-- The syntax of the ff. visualization:
SELECT *
FROM left_table 
RIGHT JOIN right_table
ON left_table.id = right_table.id;

In [2]:
import pandas as pd   
from IPython.display import display_html 

df1 = pd.DataFrame({"id": [1, 2, 3, 4], "left_val": ['L1','L2', 'L3', 'L4']})
df2 = pd.DataFrame({"id": [1, 4, 5, 6], "right_val": ['R1', 'R2', 'R3', 'R4']})
df3 = pd.DataFrame({"id": [1, 4, 5, 6], "left_val": ['L1', 'L4', 'NaN', 'NaN'], "right_val": ['R1', 'R2', 'R3','R4']})

df1_styler = df1.style.set_table_attributes("style='display:inline'").set_caption('Left table')
df2_styler = df2.style.set_table_attributes("style='display:inline'").set_caption('right table')
df3_styler = df3.style.set_table_attributes("style='display:inline'").set_caption('Result')
display_html(df1_styler._repr_html_()+df2_styler._repr_html_()+df3_styler._repr_html_(), raw=True)

## 3. FULL JOIN
- Combines `LEFT JOIN` and `RIGHT JOIN`
- The ff visualizes the `FULL JOIN`

In [ ]:
SELECT lt.id, rt.id, lt.left_val, rt.right_val
FROM left_table AS lt
FULL JOIN right_table AS rt
USING(id);

In [3]:
import pandas as pd   
from IPython.display import display_html 

df1 = pd.DataFrame({"id": [1, 2, 3, 4], "left_val": ['L1','L2', 'L3', 'L4']})
df2 = pd.DataFrame({"id": [1, 4, 5, 6], "right_val": ['R1', 'R2', 'R3', 'R4']})
df3 = pd.DataFrame({"id": [1, 2, 3, 4, 5, 6], "left_val": ['L1', 'L2', 'L3', 'L4', 'NaN', 'NaN'], "right_val": ['R1', 'NaN', 'NaN','R2', 'R3', 'R4']})

df1_styler = df1.style.set_table_attributes("style='display:inline'").set_caption('Left table')
df2_styler = df2.style.set_table_attributes("style='display:inline'").set_caption('right table')
df3_styler = df3.style.set_table_attributes("style='display:inline'").set_caption('Result')
display_html(df1_styler._repr_html_()+df2_styler._repr_html_()+df3_styler._repr_html_(), raw=True)

## 4. CROSS JOIN
- A `CROSS JOIN` produces all possible combinations of the records from both tables.
- It has **NO** `ON`

In [ ]:
-- The following visualizes the use of CROSS JOIN
SELECT table1.id, table2.id
FROM table1
CROSS JOIN table2;

In [4]:
import pandas as pd   
from IPython.display import display_html 

df1 = pd.DataFrame({"id": [1, 2]})
df2 = pd.DataFrame({"id": ['A', 'B']})
df3 = pd.DataFrame({"id": ['1A', '1B', '2A', '2B']})

df1_styler = df1.style.set_table_attributes("style='display:inline'").set_caption('table1')
df2_styler = df2.style.set_table_attributes("style='display:inline'").set_caption('table2')
df3_styler = df3.style.set_table_attributes("style='display:inline'").set_caption('Result')
display_html(df1_styler._repr_html_()+df2_styler._repr_html_()+df3_styler._repr_html_(), raw=True)

,id
0,1
1,2
,id
0,A
1,B
,id
0,1A
1,1B
2,2A
3,2B

## 5. SELF JOINS
- A self `JOIN` is when a table is joined with itself. It is used to compare rows within the same table.
- Aliasing is required

If for example, we want to _pair_ countries of the same continent, we can do this:

In [1]:
SELECT p1.country AS country1, p2.country AS country2, p1.continent
FROM world.prime_ministers AS p1
INNER JOIN world.prime_ministers AS p2
ON p1.continent = p2.continent
-- WHERE p1.country != p2.country
-- or
-- AND p1.country != p2.country
LIMIT 10;

   country1  country2      continent
0     Egypt     Egypt         Africa
1  Portugal     Spain         Europe
2  Portugal    Norway         Europe
3  Portugal  Portugal         Europe
4   Vietnam      Oman           Asia
5   Vietnam    Brunei           Asia
6   Vietnam     India           Asia
7   Vietnam   Vietnam           Asia
8     Haiti     Haiti  North America
9     India      Oman           Asia

Notice that coutries paired up with themselves, you can change that with a `WHERE` or the `AND` clause.

# Chapter 3

## 1. UNION and UNION ALL
- `UNION`: returns all distinct records from two tables
- `UNION ALL`: returns all records, including duplicates

- In here we are not merging tables but stacking them
- Fields must be in the same data type

### 1.1. UNION Visualization:

In [15]:
import pandas as pd   
from IPython.display import display_html 

df1 = pd.DataFrame({"id": [1, 2], "left_val": ['A','B']})
df2 = pd.DataFrame({"id": [1, 4, 5, 6], "right_val": ['A', 'D','E', 'F']})
df3 = pd.DataFrame({"id": [1, 2, 4, 5, 6], "left_val": ['A', 'B', 'D', 'E', 'F' ]})

df1_styler = df1.style.set_table_attributes("style='display:inline'").set_caption('Left table')
df2_styler = df2.style.set_table_attributes("style='display:inline'").set_caption('right table')
df3_styler = df3.style.set_table_attributes("style='display:inline'").set_caption('Result')
display_html(df1_styler._repr_html_()+df2_styler._repr_html_()+df3_styler._repr_html_(), raw=True)

,id,left_val
0,1,A
1,2,B
,id,right_val
0,1,A
1,4,D
2,5,E
3,6,F
,id,left_val
0,1,A
1,2,B
2,4,D
3,5,E
4,6,F

### 1.2. UNION ALL visualization:

In [16]:
import pandas as pd   
from IPython.display import display_html 

df1 = pd.DataFrame({"id": [1, 2], "left_val": ['A','B']})
df2 = pd.DataFrame({"id": [1, 4, 5, 6], "right_val": ['A', 'D','E', 'F']})
df3 = pd.DataFrame({"id": [1, 1, 2, 4, 5, 6], "left_val": ['A', 'A', 'B', 'D', 'E', 'F' ]})

df1_styler = df1.style.set_table_attributes("style='display:inline'").set_caption('Left table')
df2_styler = df2.style.set_table_attributes("style='display:inline'").set_caption('right table')
df3_styler = df3.style.set_table_attributes("style='display:inline'").set_caption('Result')
display_html(df1_styler._repr_html_()+df2_styler._repr_html_()+df3_styler._repr_html_(), raw=True)

,id,left_val
0,1,A
1,2,B
,id,right_val
0,1,A
1,4,D
2,5,E
3,6,F
,id,left_val
0,1,A
1,1,A
2,2,B
3,4,D
4,5,E
5,6,F

In here the one got repeated, so in a way it's like a union set that allows the same elements.

## 2. INTERSECT
- `INTERSECT` is a set operation that takes two tables as input and returns only the records that exist in both tables.

### 2.1. Intersect vs Inner Join
- **Since `INTERSECT` is a set operator**: `INTERSECT` requires all fields in both tables to match, and the tables must have the same number of columns.
- `INNER JOIN` adds more columns and may return duplicate records, while INTERSECT only returns unique common records.

**Intersect Visualization:**

In [1]:
import pandas as pd   
from IPython.display import display_html 

df1 = pd.DataFrame({"id": [1, 1, 3, 4], "val": ['N1','N1', 'L3', 'L4']})
df2 = pd.DataFrame({"id": [1, 4, 5, 6], "val": ['N1', 'R2','R3', 'R4']})
df3 = pd.DataFrame({"id": [1], "left_val": ['N1']})

df1_styler = df1.style.set_table_attributes("style='display:inline'").set_caption('Left table')
df2_styler = df2.style.set_table_attributes("style='display:inline'").set_caption('right table')
df3_styler = df3.style.set_table_attributes("style='display:inline'").set_caption('Result')
display_html(df1_styler._repr_html_()+df2_styler._repr_html_()+df3_styler._repr_html_(), raw=True)

,id,val
0,1,N1
1,1,N1
2,3,L3
3,4,L4
,id,val
0,1,N1
1,4,R2
2,5,R3
3,6,R4
,id,left_val
0,1,N1

If you use inner join here, you may see that if you have `JOIN`ed them on id you can find two id (1 and 1) in the result.

**Sample 1:**
Finding Countries with Prime Ministers and Presidents

In [ ]:
SELECT country FROM leaders WHERE role = 'prime_minister'
INTERSECT
SELECT country FROM leaders WHERE role = 'president';

This query returns all countries that have both a prime minister and a president.

## 3. Except
- `EXCEPT` is a set operation that helps identify records present in one table but not in another.
- Values only in the left.

In [ ]:
SELECT id, val
FROM left_table 
EXCEPT
SELECT id, val
FROM right_table;

In [2]:
import pandas as pd   
from IPython.display import display_html 

df1 = pd.DataFrame({"id": [1, 1, 3, 4], "val": ['N1','N1', 'L3', 'L4']})
df2 = pd.DataFrame({"id": [1, 4, 5, 6], "val": ['N1', 'R2','R3', 'R4']})
df3 = pd.DataFrame({"id": [3, 4], "left_val": ['L3', 'L4']})

df1_styler = df1.style.set_table_attributes("style='display:inline'").set_caption('Left table')
df2_styler = df2.style.set_table_attributes("style='display:inline'").set_caption('right table')
df3_styler = df3.style.set_table_attributes("style='display:inline'").set_caption('Result')
display_html(df1_styler._repr_html_()+df2_styler._repr_html_()+df3_styler._repr_html_(), raw=True)

,id,val
0,1,N1
1,1,N1
2,3,L3
3,4,L4
,id,val
0,1,N1
1,4,R2
2,5,R3
3,6,R4
,id,left_val
0,3,L3
1,4,L4

You can see that only 3 and 4 are the values visible in the left table.

# Chapter 4

## 1. Subquerying w/ Semi Joins and Anti Joins

ANKI THIS ONE:
- Unlike "additive" joins, which add columns to the result set, semi and anti joins **filter** records based on conditions in a related table.

### 1.1. Semi Joins
- A semi join retrieves records from the left table where a specified condition is met in the right table.
- Dapat lalabas sa result yung mga nandoon sa right table. We will use `IN` in here.

**for example**: Let's say I want to filter for countries that gain independence before 1800, I can do that with just one table containg the country and the independence year column using WHERE. But what if I also want to have the presidents thus I need another table so it is like a JOIN but instead of adding we are filtering.

In [2]:
-- example:
-- perhaps anki this
SELECT *
FROM world.countries
LIMIT 10;

  code                  name  ...   cap_long   cap_lat
0  AFG           Afghanistan  ...   69.17610  34.52280
1  NLD           Netherlands  ...    4.89095  52.37380
2  ALB               Albania  ...   19.81720  41.33170
3  DZA               Algeria  ...    3.05097  36.73970
4  ASM        American Samoa  ... -170.69100 -14.28460
5  AND               Andorra  ...    1.52180  42.50750
6  AGO                Angola  ...   13.24200  -8.81155
7  ATG   Antigua and Barbuda  ...  -61.84560  17.11750
8  ARE  United Arab Emirates  ...   54.37050  24.47640
9  ARG             Argentina  ...  -58.41730 -34.61180

[10 rows x 11 columns]

In [3]:
-- we can simply do it with this if we will be just using one table
SELECT world.countries.name
FROM world.countries
WHERE world.countries.indep_year < 1800
LIMIT 10;

             name
0     Netherlands
1         Andorra
2  United Kingdom
3           Spain
4        Ethiopia
5           Japan
6           China
7           Nepal
8        Portugal
9          France

Although the above code can be sufficient it still lacks tha column for the presidents and too bad that table does not have a president column therefore it only makes sense to use another.

In [7]:
-- This is where we can get the presidents column
SELECT world.presidents.country, world.presidents.president
FROM world.presidents
LIMIT 10;

    country                president
0     Egypt     Abdel Fattah el-Sisi
1  Portugal  Marcelo Rebelo de Sousa
2     Haiti            Jovenel Moise
3   Uruguay              Jose Mujica
4   Liberia    Ellen Johnson Sirleaf
5     Chile        Michelle Bachelet
6   Vietnam           Tran Dai Quang

In [4]:
-- But then remember that we are also tasked to add the world leaders so we can do this
SELECT world.presidents.country, world.presidents.president
FROM world.presidents

WHERE world.presidents.country IN (
SELECT world.countries.name
FROM world.countries 
WHERE world.countries.indep_year < 1800) -- remember that this query here returns what's above

LIMIT 10;

    country                president
0  Portugal  Marcelo Rebelo de Sousa

### 1.2. Anti Join
- An anti join returns records in the left table that do not match any records in a specified column of the right table.

In [12]:
-- okay, now the opposite we want to return values that are NOT IN the second table
-- the task is to return countries not in the second table (query)
-- we want to return countries name whose basic_unit is Peso

Empty DataFrame
Columns: []
Index: []

In [16]:
-- let's generate the first table first
SELECT *
FROM world.currencies;

     curr_id code            basic_unit curr_code frac_unit  frac_perbasic
0          1  AFG        Afghan afghani       AFN       Pul          100.0
1          2  ALB          Albanian lek       ALL  Qindarke          100.0
2          3  DZA        Algerian dinar       DZD   Santeem          100.0
3          4  AND                  Euro       EUR      Cent          100.0
4          5  AGO        Angolan kwanza       AOA   Centimo          100.0
..       ...  ...                   ...       ...       ...            ...
219      220  ZWE                  Euro       EUR      Cent          100.0
220      221  ZWE          Indian rupee       INR     Paisa          100.0
221      222  ZWE          Japanese yen       JPY       Sen          100.0
222      223  ZWE    South African rand       ZAR      Cent          100.0
223      224  ZWE  United States dollar       USD      Cent          100.0

[224 rows x 6 columns]

In [17]:
-- we'll filter out countries whose unit is not peso 
SELECT world.currencies.code
FROM world.currencies
WHERE world.currencies.basic_unit NOT LIKE '%peso'
LIMIT 10;

  code
0  AFG
1  ALB
2  DZA
3  AND
4  AGO
5  AIA
6  ATG
7  ARM
8  ABW
9  AUS

In [19]:
-- now, we can use that table to filter countries that use Peso, in a way it's like asking what are the countries not in the above table
SELECT world.countries.code, world.countries.name
FROM world.countries

WHERE world.countries.code NOT IN (SELECT world.currencies.code
FROM world.currencies
WHERE world.currencies.basic_unit NOT LIKE '%peso')
LIMIT 10;

  code                     name
0  ASM           American Samoa
1  ARG                Argentina
2  BHS                  Bahamas
3  VGB  Virgin Islands, British
4  CHL                    Chile
5  DOM       Dominican Republic
6  FJI             Fiji Islands
7  PHL              Philippines
8  GMB                   Gambia
9  GRL                Greenland

## 2. Subqueries within WHERE and SELECT

### 2.1. Subqueries inside where
- This is the same as what we did with Semi and Anti Joins and thus used in filtering

To identify what we need to do let us generate the tables.

In [24]:
SELECT *
FROM world.populations
LIMIT 5;

   pop_id country_code  year  fertility_rate  life_expectancy      size
0      20          ABW  2010           1.704        74.953540    101597
1      19          ABW  2015           1.647        75.573586    103889
2       2          AFG  2010           5.746        58.970830  27962208
3       1          AFG  2015           4.653        60.717170  32526562
4      12          AGO  2010           6.416        50.654170  21219954

In [25]:
-- what if we want countries and continent with life expectanct of lower than 50
SELECT world.countries.name, world.countries.continent
FROM world.countries
WHERE world.countries.code IN (SELECT world.populations.country_code
							  FROM world.populations
							  WHERE world.populations.life_expectancy < 50)
LIMIT 10;

                       name continent
0  Central African Republic    Africa
1                   Lesotho    Africa
2              Sierra Leone    Africa
3                 Swaziland    Africa
4                      Chad    Africa
5                  Zimbabwe    Africa

### 2.2. Subqueries with SELECT

- If the subquery inside `WHERE` is used for filtering subquery inside `SELECT` clause can calculate aggregated values dynamically as part of each row in the main query.
- It requires an allias which makes sense because with `SELECT` you are returning a column